# Generated by Django 5.0 on 2024-01-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('km_driven', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('ev', 'ev'), ('cng', 'cng')], default='petrol', max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=200)),
                ('date_of_purchase', models.CharField(max_length=200)),
                ('owner_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('available', 'available'), ('sold', 'sold')], default='available', max_length=200)),
            ],
        ),
    ]
