# Generated by Django 5.0 on 2024-01-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.category'),
        ),
    ]
